### ISSUE TITLE
Mac m1 support

### ISSUE THREAD

**Issue by ck37** [jianlins/quicksectx#1]
Hello,

I'm trying to install this on a mac m1 with python 3.8, but unfortunately I'm running into errors when pip installing:

```
  writing manifest file 'quicksectx.egg-info/SOURCES.txt'
  Copying quicksectx.egg-info to build/bdist.macosx-11.0-arm64/wheel/quicksectx-0.0.0-py3.8.egg-info
  running install_scripts
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/private/var/folders/q2/95q08md53wj0r4894q6_ky3w0000gr/T/pip-install-2xt89aw0/quicksectx_69ede17d43ac469f9879c1549879973e/setup.py", line 25, in <module>
      setup(name='quicksectx',
    File "/Users/user/miniforge3/envs/myenv/lib/python3.8/site-packages/setuptools/__init__.py", line 153, in setup
      return distutils.core.setup(**attrs)
    File "/Users/user/miniforge3/envs/myenv/lib/python3.8/distutils/core.py", line 148, in setup
      dist.run_commands()
    File "/Users/user/miniforge3/envs/myenv/lib/python3.8/distutils/dist.py", line 966, in run_commands
      self.run_command(cmd)
    File "/Users/user/miniforge3/envs/myenv/lib/python3.8/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/Users/user/miniforge3/envs/myenv/lib/python3.8/site-packages/wheel/bdist_wheel.py", line 328, in run
      impl_tag, abi_tag, plat_tag = self.get_tag()
    File "/Users/user/miniforge3/envs/myenv/lib/python3.8/site-packages/wheel/bdist_wheel.py", line 278, in get_tag
      assert tag in supported_tags, "would build wheel with unsupported tag {}".format(tag)
  AssertionError: would build wheel with unsupported tag ('cp38', 'cp38', 'macosx_11_0_arm64')
  ----------------------------------------
  ERROR: Failed building wheel for quicksectx
  Running setup.py clean for quicksectx
Failed to build quicksectx
```

Any ideas on how to resolve? This is in order to install medspacy.

Thanks,
Chris

**Comment by jianlins** [comment]
m1 compiled version added.

**Comment by angus-lherrou** [comment]
@jianlins could you add wheels for Python 3.9 and 3.10 for m1 as well? currently I can only see an m1 wheel for python 3.8 on PyPI

**Comment by jianlins** [comment]
added. thanks
