### ISSUE TITLE
ValueError: 'quicksect/quicksect.pyx' doesn't match any files

### ISSUE THREAD

**Issue by jsilvestri** [jianlins/quicksectx#3]
The current code available on pip is missing the pyx file and only has the .cpp file for quicksect/quicksect.cpp.  Is it possible to fix this? I ran into the problem while installing medspacy, but replicated the error in this way:

The latest version of quicksectx is here: https://pypi.org/project/quicksectx/0.3.0/ with the hashes: https://pypi.org/project/quicksectx/0.3.0/#copy-hash-modal-c1e28c50-7764-4101-97fa-c9e153bfa13a And it is missing quicksect/quicksect.pyx

```
$ curl -o quicksectx.tar.gz https://files.pythonhosted.org/packages/bb/ed/88af405793bc56aa756447450f16ff095d4ccd38cc3aa3ac1afff3983a05/quicksectx-0.3.0.tar.gz#sha256=a419f376574b1ebf6f77233d31decef7ffc89daaeda9b5da6d6b2b7ad72adddf
############################################################################################################################################################### 100.0%

$ tar xvzf quicksectx.tar.gz
x quicksectx-0.3.0/
x quicksectx-0.3.0/LICENSE
x quicksectx-0.3.0/MANIFEST.in
x quicksectx-0.3.0/PKG-INFO
x quicksectx-0.3.0/quicksect/
x quicksectx-0.3.0/quicksect/quicksect.cpp
x quicksectx-0.3.0/quicksectx/
x quicksectx-0.3.0/quicksectx/quicksectx.cp36-win_amd64.pyd
x quicksectx-0.3.0/quicksectx/quicksectx.cpp
x quicksectx-0.3.0/quicksectx/quicksectx.pxd
x quicksectx-0.3.0/quicksectx/quicksectx.pyx
x quicksectx-0.3.0/quicksectx/version.py
x quicksectx-0.3.0/quicksectx/__init__.py
x quicksectx-0.3.0/quicksectx.egg-info/
x quicksectx-0.3.0/quicksectx.egg-info/dependency_links.txt
x quicksectx-0.3.0/quicksectx.egg-info/not-zip-safe
x quicksectx-0.3.0/quicksectx.egg-info/PKG-INFO
x quicksectx-0.3.0/quicksectx.egg-info/requires.txt
x quicksectx-0.3.0/quicksectx.egg-info/SOURCES.txt
x quicksectx-0.3.0/quicksectx.egg-info/top_level.txt
x quicksectx-0.3.0/README.rst
x quicksectx-0.3.0/setup.cfg
x quicksectx-0.3.0/setup.py

$ ls quicksectx-0.3.0/quicksect
quicksect.cpp

$ pip install quicksectx-0.3.0/
Processing ./quicksectx-0.3.0
  DEPRECATION: A future pip version will change local packages to be built in-place without first copying to a temporary directory. We recommend you use --use-feature=in-tree-build to test your packages with this new behavior before it becomes the default.
   pip 21.3 will remove support for this functionality. You can find discussion regarding this at https://github.com/pypa/pip/issues/7555.
    ERROR: Command errored out with exit status 1:
     command: /Users/me/miniconda3/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/2x/g_dlkds56_bchhggqgh3t2zm0000gn/T/pip-req-build-t3u7ihru/setup.py'"'"'; __file__='"'"'/private/var/folders/2x/g_dlkds56_bchhggqgh3t2zm0000gn/T/pip-req-build-t3u7ihru/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /private/var/folders/2x/g_dlkds56_bchhggqgh3t2zm0000gn/T/pip-pip-egg-info-jq83lh3m
         cwd: /private/var/folders/2x/g_dlkds56_bchhggqgh3t2zm0000gn/T/pip-req-build-t3u7ihru/
    Complete output (12 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/2x/g_dlkds56_bchhggqgh3t2zm0000gn/T/pip-req-build-t3u7ihru/setup.py", line 50, in <module>
        ext_modules=cythonize(extensions, language_level=3, language='c++'),
      File "/Users/me/miniconda3/lib/python3.9/site-packages/Cython/Build/Dependencies.py", line 970, in cythonize
        module_list, module_metadata = create_extension_list(
      File "/Users/me/miniconda3/lib/python3.9/site-packages/Cython/Build/Dependencies.py", line 816, in create_extension_list
        for file in nonempty(sorted(extended_iglob(filepattern)), "'%s' doesn't match any files" % filepattern):
      File "/Users/me/miniconda3/lib/python3.9/site-packages/Cython/Build/Dependencies.py", line 114, in nonempty
        raise ValueError(error_msg)
    ValueError: 'quicksect/quicksect.pyx' doesn't match any files
    Warning: passing language='c++' to cythonize() is deprecated. Instead, put "# distutils: language=c++" in your .pyx or .pxd file(s)
    ----------------------------------------
WARNING: Discarding file:///Users/me/quicksectx-0.3.0. Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

**Comment by angus-lherrou** [comment]
I recommend posting the full stack trace and the command that resulted in the error

**Comment by jianlins** [comment]
Let me know if the updated version solves the issue.

**Comment by JewlsIOB** [comment]
@jianlins it worked!  Thank you!

**Comment by jsilvestri** [comment]
@jianlins this worked!  Thank you so much @angus-lherrou  and @jianlins.
