### ISSUE TITLE
package is not building in a fresh environment

### ISSUE THREAD

**Issue by DSLituiev** [jianlins/quicksectx#6]
This is the same issue as [PyRuSH #8](https://github.com/jianlins/PyRuSH/issues/8), which makes it impossible to use PyRush and quicksectx in `requirements.txt` for environment building.

```
$ pip install git+https://github.com/jianlins/quicksectx@master
Collecting git+https://github.com/jianlins/quicksectx@master
  Cloning https://github.com/jianlins/quicksectx (to revision master) to /private/var/folders/qz/tt8wl6hn2cs6rw77r5mcmll00000gp/T/pip-req-build-js7_dyam
  Running command git clone --filter=blob:none --quiet https://github.com/jianlins/quicksectx /private/var/folders/qz/tt8wl6hn2cs6rw77r5mcmll00000gp/T/pip-req-build-js7_dyam
  Resolved https://github.com/jianlins/quicksectx to commit 9086d88a0f0fdbb52c70ad65fa3f0ba1ab7a627f
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/private/var/folders/qz/tt8wl6hn2cs6rw77r5mcmll00000gp/T/pip-req-build-js7_dyam/setup.py", line 1, in <module>
          from Cython.Build import cythonize, build_ext
      ModuleNotFoundError: No module named 'Cython'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.
```

## Fix

include this into a `pyproject.toml` file the root directory:

```
[build-system]
requires = ["setuptools>=65.5.0", 'Cython>=0.29.32']
```

This enables independent installation into a fresh environment. Thank you

**Comment by jianlins** [comment]
thanks
